/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SShareIdRouteImport } from './routes/s.$shareId'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiSpeechRouteImport } from './routes/api/speech'
import { Route as ApiResumeAnalysisRouteImport } from './routes/api/resume-analysis'
import { Route as ApiRagQueryRouteImport } from './routes/api/rag-query'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppResumeRouteImport } from './routes/_authenticated/app.resume'
import { Route as AuthenticatedAppRagRouteImport } from './routes/_authenticated/app.rag'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedAppCThreadIdRouteImport } from './routes/_authenticated/app.c.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechRoute = ApiSpeechRouteImport.update({
  id: '/api/speech',
  path: '/api/speech',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeAnalysisRoute = ApiResumeAnalysisRouteImport.update({
  id: '/api/resume-analysis',
  path: '/api/resume-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagQueryRoute = ApiRagQueryRouteImport.update({
  id: '/api/rag-query',
  path: '/api/rag-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppResumeRoute = AuthenticatedAppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRagRoute = AuthenticatedAppRagRouteImport.update({
  id: '/rag',
  path: '/rag',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppCThreadIdRoute =
  AuthenticatedAppCThreadIdRouteImport.update({
    id: '/c/$threadId',
    path: '/c/$threadId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/rag-query': typeof ApiRagQueryRoute
  '/api/resume-analysis': typeof ApiResumeAnalysisRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/s/$shareId': typeof SShareIdRoute
  '/app/rag': typeof AuthenticatedAppRagRoute
  '/app/resume': typeof AuthenticatedAppResumeRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/c/$threadId': typeof AuthenticatedAppCThreadIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/rag-query': typeof ApiRagQueryRoute
  '/api/resume-analysis': typeof ApiResumeAnalysisRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/s/$shareId': typeof SShareIdRoute
  '/app/rag': typeof AuthenticatedAppRagRoute
  '/app/resume': typeof AuthenticatedAppResumeRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/c/$threadId': typeof AuthenticatedAppCThreadIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/rag-query': typeof ApiRagQueryRoute
  '/api/resume-analysis': typeof ApiResumeAnalysisRoute
  '/api/speech': typeof ApiSpeechRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/s/$shareId': typeof SShareIdRoute
  '/_authenticated/app/rag': typeof AuthenticatedAppRagRoute
  '/_authenticated/app/resume': typeof AuthenticatedAppResumeRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/c/$threadId': typeof AuthenticatedAppCThreadIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/rag-query'
    | '/api/resume-analysis'
    | '/api/speech'
    | '/api/transcribe'
    | '/s/$shareId'
    | '/app/rag'
    | '/app/resume'
    | '/app/'
    | '/app/c/$threadId'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/rag-query'
    | '/api/resume-analysis'
    | '/api/speech'
    | '/api/transcribe'
    | '/s/$shareId'
    | '/app/rag'
    | '/app/resume'
    | '/app'
    | '/app/c/$threadId'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/rag-query'
    | '/api/resume-analysis'
    | '/api/speech'
    | '/api/transcribe'
    | '/s/$shareId'
    | '/_authenticated/app/rag'
    | '/_authenticated/app/resume'
    | '/_authenticated/app/'
    | '/_authenticated/app/c/$threadId'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiRagQueryRoute: typeof ApiRagQueryRoute
  ApiResumeAnalysisRoute: typeof ApiResumeAnalysisRoute
  ApiSpeechRoute: typeof ApiSpeechRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  SShareIdRoute: typeof SShareIdRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech': {
      id: '/api/speech'
      path: '/api/speech'
      fullPath: '/api/speech'
      preLoaderRoute: typeof ApiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-analysis': {
      id: '/api/resume-analysis'
      path: '/api/resume-analysis'
      fullPath: '/api/resume-analysis'
      preLoaderRoute: typeof ApiResumeAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag-query': {
      id: '/api/rag-query'
      path: '/api/rag-query'
      fullPath: '/api/rag-query'
      preLoaderRoute: typeof ApiRagQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/resume': {
      id: '/_authenticated/app/resume'
      path: '/resume'
      fullPath: '/app/resume'
      preLoaderRoute: typeof AuthenticatedAppResumeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rag': {
      id: '/_authenticated/app/rag'
      path: '/rag'
      fullPath: '/app/rag'
      preLoaderRoute: typeof AuthenticatedAppRagRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/c/$threadId': {
      id: '/_authenticated/app/c/$threadId'
      path: '/c/$threadId'
      fullPath: '/app/c/$threadId'
      preLoaderRoute: typeof AuthenticatedAppCThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppRagRoute: typeof AuthenticatedAppRagRoute
  AuthenticatedAppResumeRoute: typeof AuthenticatedAppResumeRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCThreadIdRoute: typeof AuthenticatedAppCThreadIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppRagRoute: AuthenticatedAppRagRoute,
  AuthenticatedAppResumeRoute: AuthenticatedAppResumeRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCThreadIdRoute: AuthenticatedAppCThreadIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiRagQueryRoute: ApiRagQueryRoute,
  ApiResumeAnalysisRoute: ApiResumeAnalysisRoute,
  ApiSpeechRoute: ApiSpeechRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  SShareIdRoute: SShareIdRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
